/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace qudt4dt.thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Unit : TBase
  {
    private string _url;
    private QudtUnit _qudt_u;
    private ModelicaUnit _modelica_u;
    private MdaoUnit _mdao_u;

    public string Url
    {
      get
      {
        return _url;
      }
      set
      {
        __isset.url = true;
        this._url = value;
      }
    }

    public QudtUnit Qudt_u
    {
      get
      {
        return _qudt_u;
      }
      set
      {
        __isset.qudt_u = true;
        this._qudt_u = value;
      }
    }

    public ModelicaUnit Modelica_u
    {
      get
      {
        return _modelica_u;
      }
      set
      {
        __isset.modelica_u = true;
        this._modelica_u = value;
      }
    }

    public MdaoUnit Mdao_u
    {
      get
      {
        return _mdao_u;
      }
      set
      {
        __isset.mdao_u = true;
        this._mdao_u = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool url;
      public bool qudt_u;
      public bool modelica_u;
      public bool mdao_u;
    }

    public Unit() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Url = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Qudt_u = new QudtUnit();
              Qudt_u.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              Modelica_u = new ModelicaUnit();
              Modelica_u.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              Mdao_u = new MdaoUnit();
              Mdao_u.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Unit");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Url != null && __isset.url) {
        field.Name = "url";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Url);
        oprot.WriteFieldEnd();
      }
      if (Qudt_u != null && __isset.qudt_u) {
        field.Name = "qudt_u";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Qudt_u.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Modelica_u != null && __isset.modelica_u) {
        field.Name = "modelica_u";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        Modelica_u.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Mdao_u != null && __isset.mdao_u) {
        field.Name = "mdao_u";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        Mdao_u.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Unit(");
      bool __first = true;
      if (Url != null && __isset.url) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Url: ");
        __sb.Append(Url);
      }
      if (Qudt_u != null && __isset.qudt_u) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Qudt_u: ");
        __sb.Append(Qudt_u== null ? "<null>" : Qudt_u.ToString());
      }
      if (Modelica_u != null && __isset.modelica_u) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Modelica_u: ");
        __sb.Append(Modelica_u== null ? "<null>" : Modelica_u.ToString());
      }
      if (Mdao_u != null && __isset.mdao_u) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Mdao_u: ");
        __sb.Append(Mdao_u== null ? "<null>" : Mdao_u.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
