# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qudt.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qudt.proto',
  package='',
  serialized_pb='\n\nqudt.proto\"\x82\x01\n\x08qudtUnit\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x10\n\x08unitName\x18\x02 \x02(\t\x12\x0e\n\x06symbol\x18\x03 \x02(\t\x12\x11\n\tunitClass\x18\x04 \x02(\t\x12\x14\n\x0c\x61\x62\x62reviation\x18\x05 \x02(\t\x12\x0e\n\x06\x66\x61\x63tor\x18\x06 \x01(\x02\x12\x0e\n\x06offset\x18\x07 \x01(\x02')




_QUDTUNIT = _descriptor.Descriptor(
  name='qudtUnit',
  full_name='qudtUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='qudtUnit.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unitName', full_name='qudtUnit.unitName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='qudtUnit.symbol', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unitClass', full_name='qudtUnit.unitClass', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abbreviation', full_name='qudtUnit.abbreviation', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factor', full_name='qudtUnit.factor', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='qudtUnit.offset', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['qudtUnit'] = _QUDTUNIT

class qudtUnit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUDTUNIT

  # @@protoc_insertion_point(class_scope:qudtUnit)


# @@protoc_insertion_point(module_scope)
