# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qudt.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qudt.proto',
  package='',
  serialized_pb='\n\nqudt.proto\"\x82\x01\n\x08QudtUnit\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x10\n\x08unitName\x18\x02 \x02(\t\x12\x0e\n\x06symbol\x18\x03 \x02(\t\x12\x11\n\tunitClass\x18\x04 \x02(\t\x12\x14\n\x0c\x61\x62\x62reviation\x18\x05 \x02(\t\x12\x0e\n\x06\x66\x61\x63tor\x18\x06 \x01(\x02\x12\x0e\n\x06offset\x18\x07 \x01(\x02\"q\n\x0cModelicaUnit\x12\x11\n\tclassPath\x18\x01 \x02(\t\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\x0b\n\x03min\x18\x03 \x01(\x02\x12\r\n\x05start\x18\x04 \x01(\x02\x12\x13\n\x0b\x64isplayUnit\x18\x05 \x01(\t\x12\x10\n\x08quantity\x18\x06 \x02(\t\"=\n\x08MdaoUnit\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\nexpression\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\"h\n\x04Unit\x12\x1c\n\tqudt_unit\x18\x01 \x02(\x0b\x32\t.QudtUnit\x12$\n\rmodelica_unit\x18\x02 \x01(\x0b\x32\r.ModelicaUnit\x12\x1c\n\tmdao_unit\x18\x03 \x01(\x0b\x32\t.MdaoUnit')




_QUDTUNIT = _descriptor.Descriptor(
  name='QudtUnit',
  full_name='QudtUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='QudtUnit.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unitName', full_name='QudtUnit.unitName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='QudtUnit.symbol', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unitClass', full_name='QudtUnit.unitClass', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abbreviation', full_name='QudtUnit.abbreviation', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factor', full_name='QudtUnit.factor', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='QudtUnit.offset', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=145,
)


_MODELICAUNIT = _descriptor.Descriptor(
  name='ModelicaUnit',
  full_name='ModelicaUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classPath', full_name='ModelicaUnit.classPath', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='ModelicaUnit.max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='ModelicaUnit.min', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='ModelicaUnit.start', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayUnit', full_name='ModelicaUnit.displayUnit', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='ModelicaUnit.quantity', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=147,
  serialized_end=260,
)


_MDAOUNIT = _descriptor.Descriptor(
  name='MdaoUnit',
  full_name='MdaoUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MdaoUnit.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expression', full_name='MdaoUnit.expression', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='MdaoUnit.comment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=262,
  serialized_end=323,
)


_UNIT = _descriptor.Descriptor(
  name='Unit',
  full_name='Unit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qudt_unit', full_name='Unit.qudt_unit', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelica_unit', full_name='Unit.modelica_unit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mdao_unit', full_name='Unit.mdao_unit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=325,
  serialized_end=429,
)

_UNIT.fields_by_name['qudt_unit'].message_type = _QUDTUNIT
_UNIT.fields_by_name['modelica_unit'].message_type = _MODELICAUNIT
_UNIT.fields_by_name['mdao_unit'].message_type = _MDAOUNIT
DESCRIPTOR.message_types_by_name['QudtUnit'] = _QUDTUNIT
DESCRIPTOR.message_types_by_name['ModelicaUnit'] = _MODELICAUNIT
DESCRIPTOR.message_types_by_name['MdaoUnit'] = _MDAOUNIT
DESCRIPTOR.message_types_by_name['Unit'] = _UNIT

class QudtUnit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUDTUNIT

  # @@protoc_insertion_point(class_scope:QudtUnit)

class ModelicaUnit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODELICAUNIT

  # @@protoc_insertion_point(class_scope:ModelicaUnit)

class MdaoUnit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MDAOUNIT

  # @@protoc_insertion_point(class_scope:MdaoUnit)

class Unit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNIT

  # @@protoc_insertion_point(class_scope:Unit)


# @@protoc_insertion_point(module_scope)
