//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS.GME.Dsml.qudtUnit.Classes
{
	using global::System.Linq;
	
	
	/// <summary>
	///<para>This API code is compatible with the following paradigm:</para>
	///<para> - Name: qudtUnit</para>
	///<para> - Guid: {FBBDB662-E086-4057-8964-36D70144D2AB}</para>
	///<para>Additional information: </para>
	///<para> - Date: 5/22/2014 4:42:33 PM</para>
	///<para> - Author: </para>
	///<para> - Version: </para>
	///<para> - Comment: </para>
	///</summary>
	///
	/// <summary>
	/// </summary>
	public class RootFolder : ISIS.GME.Common.Classes.RootFolder, ISIS.GME.Dsml.qudtUnit.Interfaces.RootFolder
	{
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public override global::System.Collections.Generic.Dictionary<int, global::System.Type> MetaRefs
		{
			get
			{
				return new global::System.Collections.Generic.Dictionary<int, global::System.Type>()
{
{1000, typeof(RootFolder) },
{1003, typeof(Node) },
{1004, typeof(Edge) },
{1005, typeof(Main) }
}
;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public ISIS.GME.Dsml.qudtUnit.Classes.RootFolder.InfoClass Info
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.RootFolder.InfoClass();
			}
		}
		
		/// <summary>
		///<para>Contains the library's connection string if this object is an attached library.</para>
		///<para></para>
		///</summary>
		public string LibraryName
		{
			get
			{
				return (Impl as global::GME.MGA.MgaFolder).LibraryName;
			}
		}
		
		/// <summary>
		///<para>Contains the domain specific attached libraries.</para>
		///<para></para>
		///</summary>
		public global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.RootFolder> LibraryCollection
		{
			get
			{
				return ISIS.GME.Common.Utils.CastMgaChildren<ISIS.GME.Dsml.qudtUnit.Classes.RootFolder, global::GME.MGA.MgaObjects>(Impl.ChildObjects, "RootFolder");
			}
		}
		
		/// <para>Represents the domain specific parent container.</para>
		///<para></para>
		public override ISIS.GME.Common.Interfaces.Container ParentContainer
		{
			get
			{
if ((Impl as global::GME.MGA.MgaFolder).ParentFolder != null) { return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.RootFolder>((Impl as global::GME.MGA.MgaFolder).ParentFolder as global::GME.MGA.MgaObject); }
				return null;
			}
		}
		
		/// <summary>
		///<para>Contains the domain specific child objects.</para>
		///<para></para>
		///</summary>
		RootFolder.ChildrenClass ISIS.GME.Dsml.qudtUnit.Interfaces.RootFolder.Children
		{
			get
			{
				return new RootFolder.ChildrenClass(((global::GME.MGA.MgaFolder)(this.Impl)));
			}
		}
		
		/// <summary>
		///<para>Contains all the domain specific child objects.</para>
		///<para></para>
		///</summary>
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> AllChildren
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> result = ISIS.GME.Common.Utils.CastMgaChildren<ISIS.GME.Dsml.qudtUnit.Classes.RootFolder, global::GME.MGA.MgaObjects>(Impl.ChildObjects, "RootFolder");
				result = result.Concat(ISIS.GME.Common.Utils.CastMgaChildren<ISIS.GME.Dsml.qudtUnit.Classes.Main, global::GME.MGA.MgaObjects>(Impl.ChildObjects, 1005/*"Main"*/));
				return result;
			}
		}
		
		/// Gets the root folder form an Mga project.
		public new static ISIS.GME.Dsml.qudtUnit.Interfaces.RootFolder GetRootFolder(global::GME.MGA.MgaProject project)
		{
			return ISIS.GME.Common.Utils.CreateObject<RootFolder>(project.RootFolder as global::GME.MGA.MgaObject);
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class InfoClass
		{
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public global::System.Guid ParadigmGuid
			{
				get
				{
					return new global::System.Guid("{FBBDB662-E086-4057-8964-36D70144D2AB}");
				}
			}
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public string ParadigmName
			{
				get
				{
					return "qudtUnit";
				}
			}
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public string ParadigmVersion
			{
				get
				{
					return "";
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class ChildrenClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			private global::GME.MGA.MgaFolder ImplFolder;
			
			private global::GME.MGA.MgaModel ImplModel;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ChildrenClass(global::GME.MGA.MgaFolder impl)
			{
				this.ImplFolder = impl;
				this.Impl = ((global::GME.MGA.IMgaObject)(impl));
			}
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ChildrenClass(global::GME.MGA.MgaModel impl)
			{
				this.ImplModel = impl;
				this.Impl = ((global::GME.MGA.IMgaObject)(impl));
			}
			
			/// <summary>
			///<para>
			///Retirves with specific kinds in the container.
			///</para>
			///</summary>
			///
			public global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Main> MainCollection
			{
				get
				{
global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Main> result = ISIS.GME.Common.Utils.CastMgaChildren<ISIS.GME.Dsml.qudtUnit.Classes.Main, global::GME.MGA.MgaObjects>(Impl.ChildObjects, "Main" /* 1005 */);
return result;
				}
			}
		}
	}
	
	/// <summary>
	/// </summary>
	public class Edge : ISIS.GME.Common.Classes.Connection, ISIS.GME.Dsml.qudtUnit.Interfaces.Edge
	{
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Interfaces.Edge ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.ArcheType
		{
			get
			{
				return (Impl as global::GME.MGA.MgaFCO).ArcheType == null ? null : ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Edge>((Impl as global::GME.MGA.MgaFCO).ArcheType as global::GME.MGA.MgaObject);
			}
		}
		
		/// 
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get
			{
				return new ISIS.GME.Common.Interfaces.Connection[] {};
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.SrcConnectionsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.SrcConnections
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Edge.SrcConnectionsClass(Impl);
			}
		}
		
		/// 
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get
			{
				return new ISIS.GME.Common.Interfaces.Connection[] {};
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.DstConnectionsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.DstConnections
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Edge.DstConnectionsClass(Impl);
			}
		}
		
		/// 
		public override ISIS.GME.Common.Interfaces.FCO SrcEnd
		{
			get
			{
				return (new ISIS.GME.Common.Interfaces.FCO[] { ((ISIS.GME.Dsml.qudtUnit.Interfaces.Edge)(this)).SrcEnds.Node, 
}).FirstOrDefault(x => x != null);
			}
		}
		
		Edge.SrcEndsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.SrcEnds
		{
			get
			{
				return new Edge.SrcEndsClass(Impl);
			}
		}
		
		/// 
		public override ISIS.GME.Common.Interfaces.FCO DstEnd
		{
			get
			{
				return (new ISIS.GME.Common.Interfaces.FCO[] { ((ISIS.GME.Dsml.qudtUnit.Interfaces.Edge)(this)).DstEnds.Node, 
}).FirstOrDefault(x => x != null);
			}
		}
		
		Edge.DstEndsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.DstEnds
		{
			get
			{
				return new Edge.DstEndsClass(Impl);
			}
		}
		
		/// <summary>
		///<para>Represents the domain specific parent container.</para>
		///<para></para>
		///<para>
		///----------------------------------------------------
		///</para>
		///<para>
		///The parent could be:
		///</para>
		///<para>
		///- Main [Model]
		///</para>
		///</summary>
		///
		public override ISIS.GME.Common.Interfaces.Container ParentContainer
		{
			get
			{
global::GME.MGA.MgaObject parentFolder = (this.Impl as global::GME.MGA.MgaFCO).ParentFolder as global::GME.MGA.MgaObject;
global::GME.MGA.MgaObject parentModel = (this.Impl as global::GME.MGA.MgaFCO).ParentModel as global::GME.MGA.MgaObject;
if (parentModel != null && parentModel.MetaBase.MetaRef == 1005/*"Main"*/) { return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Main>(parentModel); }
				return null;
			}
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.AttributesClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.Attributes
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Edge.AttributesClass(this.Impl);
			}
		}
		
		/// 
		public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> result = ISIS.GME.Common.Utils.CastReferencedBy(Impl as global::GME.MGA.MgaFCO, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() {
});
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.ReferencedByClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.ReferencedBy
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Edge.ReferencedByClass(Impl);
			}
		}
		
		/// 
		public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> result = ISIS.GME.Common.Utils.CastMembersOfSet(Impl as global::GME.MGA.MgaFCO, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() {
});
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.MembersOfSetClass ISIS.GME.Dsml.qudtUnit.Interfaces.Edge.MembersOfSet
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Edge.MembersOfSetClass(Impl);
			}
		}
		
		/// <summary>
		///Creates a new Edge connection.
		///</summary>
		///<param name="src">
		///<para>Source of the connection, which could be:</para>
		///<para>- Node</para>
		///</param>
		///<param name="dst">
		///<para>Destination of the connection, which could be:</para>
		///<para>- Node</para>
		///</param>
		///<param name="srcRef">
		///<para>Source reference parent.</para>
		///</param>
		///<param name="dstRef">
		///<para>Destination reference parent.</para>
		///</param>
		///<param name="parent">
		///<para>Parent of the connection, which could be:</para>
		///<para>- Main</para>
		///</param>
		///<param name="role">
		///<para>Role of the connection</para>
		///</param>
		///<returns>The connection object, which has been created.</returns>
		///
		public static ISIS.GME.Dsml.qudtUnit.Interfaces.Edge Connect(ISIS.GME.Dsml.qudtUnit.Interfaces.Node src, ISIS.GME.Dsml.qudtUnit.Interfaces.Node dst, ISIS.GME.Common.Interfaces.Reference srcRef = null, ISIS.GME.Common.Interfaces.Reference dstRef = null, ISIS.GME.Dsml.qudtUnit.Interfaces.Main parent = null, DefaultRole role = DefaultRole.Edge)
		{
			return ISIS.GME.Common.Utils.MakeConnection<ISIS.GME.Dsml.qudtUnit.Classes.Edge>(src, dst, srcRef, dstRef, parent, "" + role.ToString());
		}
		
		/// <summary>
		/// Gets a domain specific object from a COM object.
		/// </summary>
		public static ISIS.GME.Dsml.qudtUnit.Interfaces.Edge Cast(global::GME.MGA.IMgaObject subject)
		{
			return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Edge>(subject);
		}
		
		/// Default role
		public enum DefaultRole
		{
			
			/// <summary>
			/// Default role
			/// </summary>
			Edge,
		}
		
		/// <summary>
		///<para>WARNING: This part is still under developement.</para>
		///<para></para>
		///</summary>
		public struct Roles
		{
			
			/// Roles for Main parent.
			public enum Main
			{
				
				/// <summary>
				/// Edge
				/// </summary>
				Edge = 1006,
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class SrcConnectionsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public SrcConnectionsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class DstConnectionsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public DstConnectionsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class SrcEndsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public SrcEndsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
			
			/// <summary>
			/// Src ends. NOTE: Does not contain derived classes. Type must exactly match otherwise it is null.
			/// <para>
			///-----------------------------------------
			///</para>
			///<para>
			///Type could be:
			///</para>
			///<para>
			///- Node
			///</para>
			///
			/// </summary>
			public virtual ISIS.GME.Dsml.qudtUnit.Interfaces.Node Node
			{
				get
				{
ISIS.GME.Dsml.qudtUnit.Interfaces.Node result = null;
result = ISIS.GME.Common.Utils.CastSrcEnd<ISIS.GME.Dsml.qudtUnit.Classes.Node, global::GME.MGA.MgaFCO>(Impl as global::GME.MGA.MgaFCO, "Node");
					if (result != null) { return result; };
					return result;
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class DstEndsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public DstEndsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
			
			/// <summary>
			/// Dst ends. NOTE: Does not contain derived classes. Type must exactly match otherwise it is null.
			/// <para>
			///-----------------------------------------
			///</para>
			///<para>
			///Type could be:
			///</para>
			///<para>
			///- Node
			///</para>
			///
			/// </summary>
			public virtual ISIS.GME.Dsml.qudtUnit.Interfaces.Node Node
			{
				get
				{
ISIS.GME.Dsml.qudtUnit.Interfaces.Node result = null;
result = ISIS.GME.Common.Utils.CastDstEnd<ISIS.GME.Dsml.qudtUnit.Classes.Node, global::GME.MGA.MgaFCO>(Impl as global::GME.MGA.MgaFCO, "Node");
					if (result != null) { return result; };
					return result;
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class AttributesClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public AttributesClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class ReferencedByClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ReferencedByClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class MembersOfSetClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public MembersOfSetClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
	}
	
	/// <summary>
	/// </summary>
	public class Node : ISIS.GME.Common.Classes.Atom, ISIS.GME.Dsml.qudtUnit.Interfaces.Node
	{
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Interfaces.Node ISIS.GME.Dsml.qudtUnit.Interfaces.Node.ArcheType
		{
			get
			{
				return (Impl as global::GME.MGA.MgaFCO).ArcheType == null ? null : ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Node>((Impl as global::GME.MGA.MgaFCO).ArcheType as global::GME.MGA.MgaObject);
			}
		}
		
		/// 
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> result = ((ISIS.GME.Dsml.qudtUnit.Interfaces.Node)(this)).SrcConnections.EdgeCollection.Cast<ISIS.GME.Common.Interfaces.Connection>();
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Node.SrcConnectionsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Node.SrcConnections
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Node.SrcConnectionsClass(Impl);
			}
		}
		
		/// 
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> result = ((ISIS.GME.Dsml.qudtUnit.Interfaces.Node)(this)).DstConnections.EdgeCollection.Cast<ISIS.GME.Common.Interfaces.Connection>();
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Node.DstConnectionsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Node.DstConnections
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Node.DstConnectionsClass(Impl);
			}
		}
		
		/// <summary>
		///<para>Represents the domain specific parent container.</para>
		///<para></para>
		///<para>
		///----------------------------------------------------
		///</para>
		///<para>
		///The parent could be:
		///</para>
		///<para>
		///- Main [Model]
		///</para>
		///</summary>
		///
		public override ISIS.GME.Common.Interfaces.Container ParentContainer
		{
			get
			{
global::GME.MGA.MgaObject parentFolder = (this.Impl as global::GME.MGA.MgaFCO).ParentFolder as global::GME.MGA.MgaObject;
global::GME.MGA.MgaObject parentModel = (this.Impl as global::GME.MGA.MgaFCO).ParentModel as global::GME.MGA.MgaObject;
if (parentModel != null && parentModel.MetaBase.MetaRef == 1005/*"Main"*/) { return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Main>(parentModel); }
				return null;
			}
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Node.AttributesClass ISIS.GME.Dsml.qudtUnit.Interfaces.Node.Attributes
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Node.AttributesClass(this.Impl);
			}
		}
		
		/// 
		public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> result = ISIS.GME.Common.Utils.CastReferencedBy(Impl as global::GME.MGA.MgaFCO, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() {
});
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Node.ReferencedByClass ISIS.GME.Dsml.qudtUnit.Interfaces.Node.ReferencedBy
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Node.ReferencedByClass(Impl);
			}
		}
		
		/// 
		public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> result = ISIS.GME.Common.Utils.CastMembersOfSet(Impl as global::GME.MGA.MgaFCO, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() {
});
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Node.MembersOfSetClass ISIS.GME.Dsml.qudtUnit.Interfaces.Node.MembersOfSet
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Node.MembersOfSetClass(Impl);
			}
		}
		
		/// Creates an object in a container.
		public static ISIS.GME.Dsml.qudtUnit.Interfaces.Node Create(ISIS.GME.Dsml.qudtUnit.Interfaces.Main parent, DefaultRole roleStr = DefaultRole.Node)
		{
			return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Node>(parent, "" + roleStr.ToString());
		}
		
		/// <summary>
		/// Gets a domain specific object from a COM object.
		/// </summary>
		public static ISIS.GME.Dsml.qudtUnit.Interfaces.Node Cast(global::GME.MGA.IMgaObject subject)
		{
			return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Node>(subject);
		}
		
		/// Default role
		public enum DefaultRole
		{
			
			/// <summary>
			/// Default role
			/// </summary>
			Node,
		}
		
		/// <summary>
		///<para>WARNING: This part is still under developement.</para>
		///<para></para>
		///</summary>
		public struct Roles
		{
			
			/// Roles for Main parent.
			public enum Main
			{
				
				/// <summary>
				/// Node
				/// </summary>
				Node = 1007,
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class SrcConnectionsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public SrcConnectionsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
			
			/// <summary>
			///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
			///<para></para>
			///</summary>
			public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Edge> EdgeCollection
			{
				get
				{
					return ISIS.GME.Common.Utils.CastSrcConnections<ISIS.GME.Dsml.qudtUnit.Classes.Edge, global::GME.MGA.MgaFCO>(Impl as global::GME.MGA.MgaFCO, "Edge");
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class DstConnectionsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public DstConnectionsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
			
			/// <summary>
			///<para>Retrieves all connections, which have this object as a SOURCE.</para>
			///<para></para>
			///</summary>
			public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Edge> EdgeCollection
			{
				get
				{
					return ISIS.GME.Common.Utils.CastDstConnections<ISIS.GME.Dsml.qudtUnit.Classes.Edge, global::GME.MGA.MgaFCO>(Impl as global::GME.MGA.MgaFCO, "Edge");
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class AttributesClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public AttributesClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
			
			/// <summary>
			/// <para>Value attribute</para>
			/// </summary>
			public string Value
			{
				get
				{
					return ((global::GME.MGA.MgaFCO)(Impl)).StrAttrByName["Value"];
				}
				set
				{
					((global::GME.MGA.MgaFCO)(Impl)).StrAttrByName["Value"] = value;
				}
			}
			
			/// <summary>
			/// <para>UnitName attribute</para>
			/// </summary>
			public string UnitName
			{
				get
				{
					return ((global::GME.MGA.MgaFCO)(Impl)).StrAttrByName["UnitName"];
				}
				set
				{
					((global::GME.MGA.MgaFCO)(Impl)).StrAttrByName["UnitName"] = value;
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class ReferencedByClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ReferencedByClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class MembersOfSetClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public MembersOfSetClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
	}
	
	/// <summary>
	/// </summary>
	public class Main : ISIS.GME.Common.Classes.Model, ISIS.GME.Dsml.qudtUnit.Interfaces.Main
	{
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Interfaces.Main ISIS.GME.Dsml.qudtUnit.Interfaces.Main.ArcheType
		{
			get
			{
				return (Impl as global::GME.MGA.MgaFCO).ArcheType == null ? null : ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Main>((Impl as global::GME.MGA.MgaFCO).ArcheType as global::GME.MGA.MgaObject);
			}
		}
		
		/// 
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get
			{
				return new ISIS.GME.Common.Interfaces.Connection[] {};
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Main.SrcConnectionsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Main.SrcConnections
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Main.SrcConnectionsClass(Impl);
			}
		}
		
		/// 
		public override global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get
			{
				return new ISIS.GME.Common.Interfaces.Connection[] {};
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Main.DstConnectionsClass ISIS.GME.Dsml.qudtUnit.Interfaces.Main.DstConnections
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Main.DstConnectionsClass(Impl);
			}
		}
		
		/// <summary>
		///<para>Represents the domain specific parent container.</para>
		///<para></para>
		///<para>
		///----------------------------------------------------
		///</para>
		///<para>
		///The parent could be:
		///</para>
		///<para>
		///- RootFolder [Folder]
		///</para>
		///</summary>
		///
		public override ISIS.GME.Common.Interfaces.Container ParentContainer
		{
			get
			{
global::GME.MGA.MgaObject parentFolder = (this.Impl as global::GME.MGA.MgaFCO).ParentFolder as global::GME.MGA.MgaObject;
if (parentFolder != null && parentFolder.MetaBase.MetaRef == 1000/*"RootFolder"*/) { return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.RootFolder>(parentFolder); }
global::GME.MGA.MgaObject parentModel = (this.Impl as global::GME.MGA.MgaFCO).ParentModel as global::GME.MGA.MgaObject;
				return null;
			}
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.AttributesClass ISIS.GME.Dsml.qudtUnit.Interfaces.Main.Attributes
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Main.AttributesClass(this.Impl);
			}
		}
		
		/// <summary>
		///<para>Contains the domain specific child objects.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.ChildrenClass ISIS.GME.Dsml.qudtUnit.Interfaces.Main.Children
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Main.ChildrenClass(((global::GME.MGA.MgaModel)(this.Impl)));
			}
		}
		
		/// <summary>
		///<para>Contains all the domain specific child objects.</para>
		///<para></para>
		///</summary>
		public override global::System.Collections.Generic.IEnumerable<global::ISIS.GME.Common.Interfaces.Base> AllChildren
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> result = ISIS.GME.Common.Utils.CastMgaChildren(Impl.ChildObjects, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() { 
{ 1003 /*Node*/ , typeof(ISIS.GME.Dsml.qudtUnit.Classes.Node ) },
{ 1004 /*Edge*/ , typeof(ISIS.GME.Dsml.qudtUnit.Classes.Edge ) },
});
;
				return result;
			}
		}
		
		/// 
		public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> result = ISIS.GME.Common.Utils.CastReferencedBy(Impl as global::GME.MGA.MgaFCO, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() {
});
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Main.ReferencedByClass ISIS.GME.Dsml.qudtUnit.Interfaces.Main.ReferencedBy
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Main.ReferencedByClass(Impl);
			}
		}
		
		/// 
		public virtual global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get
			{
				global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> result = ISIS.GME.Common.Utils.CastMembersOfSet(Impl as global::GME.MGA.MgaFCO, new global::System.Collections.Generic.Dictionary<int, global::System.Type>() {
});
				return result;
			}
		}
		
		ISIS.GME.Dsml.qudtUnit.Classes.Main.MembersOfSetClass ISIS.GME.Dsml.qudtUnit.Interfaces.Main.MembersOfSet
		{
			get
			{
				return new ISIS.GME.Dsml.qudtUnit.Classes.Main.MembersOfSetClass(Impl);
			}
		}
		
		/// Creates an object in the RootFolder.
		public static ISIS.GME.Dsml.qudtUnit.Interfaces.Main Create(ISIS.GME.Dsml.qudtUnit.Interfaces.RootFolder parent)
		{
			return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Main>(parent);
		}
		
		/// <summary>
		/// Gets a domain specific object from a COM object.
		/// </summary>
		public static ISIS.GME.Dsml.qudtUnit.Interfaces.Main Cast(global::GME.MGA.IMgaObject subject)
		{
			return ISIS.GME.Common.Utils.CreateObject<ISIS.GME.Dsml.qudtUnit.Classes.Main>(subject);
		}
		
		/// Default role
		public enum DefaultRole
		{
			
			/// <summary>
			/// Default role
			/// </summary>
			Main,
		}
		
		/// <summary>
		///<para>WARNING: This part is still under developement.</para>
		///<para></para>
		///</summary>
		public struct Roles
		{
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class SrcConnectionsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public SrcConnectionsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class DstConnectionsClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public DstConnectionsClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class AttributesClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public AttributesClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class ChildrenClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			private global::GME.MGA.MgaFolder ImplFolder;
			
			private global::GME.MGA.MgaModel ImplModel;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ChildrenClass(global::GME.MGA.MgaFolder impl)
			{
				this.ImplFolder = impl;
				this.Impl = ((global::GME.MGA.IMgaObject)(impl));
			}
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ChildrenClass(global::GME.MGA.MgaModel impl)
			{
				this.ImplModel = impl;
				this.Impl = ((global::GME.MGA.IMgaObject)(impl));
			}
			
			/// <summary>
			///<para>
			///Retirves with specific kinds in the container.
			///</para>
			///</summary>
			///
			public global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Node> NodeCollection
			{
				get
				{
global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Node> result = ISIS.GME.Common.Utils.CastMgaChildren<ISIS.GME.Dsml.qudtUnit.Classes.Node, global::GME.MGA.MgaObjects>(Impl.ChildObjects, "Node" /* 1003 */);
return result;
				}
			}
			
			/// <summary>
			///<para>
			///Retirves with specific kinds in the container.
			///</para>
			///</summary>
			///
			public global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Edge> EdgeCollection
			{
				get
				{
global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.Edge> result = ISIS.GME.Common.Utils.CastMgaChildren<ISIS.GME.Dsml.qudtUnit.Classes.Edge, global::GME.MGA.MgaObjects>(Impl.ChildObjects, "Edge" /* 1004 */);
return result;
				}
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class ReferencedByClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public ReferencedByClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		public class MembersOfSetClass
		{
			
			private global::GME.MGA.IMgaObject Impl;
			
			/// <summary>
			///<para></para>
			///<para></para>
			///</summary>
			public MembersOfSetClass(global::GME.MGA.IMgaObject impl)
			{
				this.Impl = impl;
			}
		}
	}
}
namespace ISIS.GME.Dsml.qudtUnit.Interfaces
{
	
	
	/// <summary>
	///<para>This API code is compatible with the following paradigm:</para>
	///<para> - Name: qudtUnit</para>
	///<para> - Guid: {FBBDB662-E086-4057-8964-36D70144D2AB}</para>
	///<para>Additional information: </para>
	///<para> - Date: 5/22/2014 4:42:33 PM</para>
	///<para> - Author: </para>
	///<para> - Version: </para>
	///<para> - Comment: </para>
	///</summary>
	///
	/// <summary>
	/// <para>RootFolder interface</para>
	/// </summary>
	public interface RootFolder : ISIS.GME.Common.Interfaces.RootFolder
	{
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.RootFolder.InfoClass Info
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		new global::System.Collections.Generic.Dictionary<int, global::System.Type> MetaRefs
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the library's connection string if this object is an attached library.</para>
		///<para></para>
		///</summary>
		string LibraryName
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attached libraries.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.qudtUnit.Interfaces.RootFolder> LibraryCollection
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific child objects.</para>
		///<para></para>
		///</summary>
		Classes.RootFolder.ChildrenClass Children
		{
			get;
		}
		
		/// <summary>
		///<para>Contains all the domain specific child objects.</para>
		///<para></para>
		///</summary>
		new global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> AllChildren
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>Edge interface</para>
	/// </summary>
	public interface Edge : ISIS.GME.Common.Interfaces.Connection
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Common.Interfaces.FCO SrcEnd
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.SrcEndsClass SrcEnds
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Common.Interfaces.FCO DstEnd
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.DstEndsClass DstEnds
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Interfaces.Edge ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Edge.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>Node interface</para>
	/// </summary>
	public interface Node : ISIS.GME.Common.Interfaces.Atom
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Node.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Node.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Interfaces.Node ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Node.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Node.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Node.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>Main interface</para>
	/// </summary>
	public interface Main : ISIS.GME.Common.Interfaces.Model
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Interfaces.Main ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific child objects.</para>
		///<para></para>
		///</summary>
		Classes.Main.ChildrenClass Children
		{
			get;
		}
		
		/// <summary>
		///<para>Contains all the domain specific child objects.</para>
		///<para></para>
		///</summary>
		new global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> AllChildren
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.qudtUnit.Classes.Main.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
}
