/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace qudt4dt.thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Unit : TBase
  {
    private string _url;
    private string _qudt_url;
    private QudtAttr _qudt_attr;

    public string Url
    {
      get
      {
        return _url;
      }
      set
      {
        __isset.url = true;
        this._url = value;
      }
    }

    public string Qudt_url
    {
      get
      {
        return _qudt_url;
      }
      set
      {
        __isset.qudt_url = true;
        this._qudt_url = value;
      }
    }

    public QudtAttr Qudt_attr
    {
      get
      {
        return _qudt_attr;
      }
      set
      {
        __isset.qudt_attr = true;
        this._qudt_attr = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool url;
      public bool qudt_url;
      public bool qudt_attr;
    }

    public Unit() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Url = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Qudt_url = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              Qudt_attr = new QudtAttr();
              Qudt_attr.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Unit");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Url != null && __isset.url) {
        field.Name = "url";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Url);
        oprot.WriteFieldEnd();
      }
      if (Qudt_url != null && __isset.qudt_url) {
        field.Name = "qudt_url";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Qudt_url);
        oprot.WriteFieldEnd();
      }
      if (Qudt_attr != null && __isset.qudt_attr) {
        field.Name = "qudt_attr";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        Qudt_attr.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Unit(");
      bool __first = true;
      if (Url != null && __isset.url) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Url: ");
        __sb.Append(Url);
      }
      if (Qudt_url != null && __isset.qudt_url) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Qudt_url: ");
        __sb.Append(Qudt_url);
      }
      if (Qudt_attr != null && __isset.qudt_attr) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Qudt_attr: ");
        __sb.Append(Qudt_attr== null ? "<null>" : Qudt_attr.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
